version: '2.2'
services:
  db:
    container_name: ecommerce-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - /var/lib/postgresql/data
    networks:
      - ecommerce
  
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../backend
    volumes:
      - ../backend:/usr/src/app
    env_file:
    - .env
    command: yarn start:dev
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  ecommerce:
    external:
      name: ecommerce


  